[package]
name = "earth-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
# Windowing and graphics
winit = "0.29"
wgpu = "0.19"

# Math
cgmath = "0.18"
glam = { version = "0.25", features = ["serde"] }

# Noise generation
noise = "0.8"

# Serialization
bytemuck = { version = "1.14", features = ["derive"] }

# Logging
log = "0.4"
env_logger = "0.11"

# Async runtime for wgpu  
pollster = "0.3"

# Image loading (for future textures)
image = "0.24"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Random number generation
rand = "0.8"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

# Compression
flate2 = "1.0"
zstd = "0.13"
lz4_flex = "0.11"

# Archive
tar = "0.4"

# Checksums
crc32fast = "1.3"

# Date/time
chrono = "0.4"

# Async utilities
futures = "0.3"
tokio = { version = "1.40", features = ["macros", "rt-multi-thread"] }

# Parallel processing
rayon = "1.8"
dashmap = "5.5"
parking_lot = "0.12"
crossbeam-channel = "0.5"
num_cpus = "1.16"

[dev-dependencies]
tempfile = "3.10"

[[example]]
name = "inventory_system"
path = "examples/inventory_system.rs"

[[example]]
name = "crafting_system"
path = "examples/crafting_system.rs"

[[example]]
name = "multiplayer"
path = "examples/multiplayer.rs"

[[bin]]
name = "parallel_benchmark"
path = "src/bin/parallel_benchmark.rs"

[[bin]]
name = "parallel_test"
path = "src/bin/parallel_test.rs"

[[bin]]
name = "async_mesh_benchmark"
path = "src/bin/async_mesh_benchmark.rs"

[[bin]]
name = "async_render_test"
path = "src/bin/async_render_test.rs"

[[bin]]
name = "parallel_lighting_benchmark"
path = "src/bin/parallel_lighting_benchmark.rs"

[[bin]]
name = "parallel_lighting_test"
path = "src/bin/parallel_lighting_test.rs"

[[bin]]
name = "profile_baseline"
path = "src/bin/profile_baseline.rs"

[[bin]]
name = "analyze_hot_paths"
path = "src/bin/analyze_hot_paths.rs"

[[bin]]
name = "soa_benchmark"
path = "src/bin/soa_benchmark.rs"

[[bin]]
name = "gpu_driven_test"
path = "src/bin/gpu_driven_test.rs"